### ISSUE TITLE
增加功能：显示zk服务器状态

### ISSUE THREAD

**Issue by pugwoo** [xin497668869/zookeeper-visualizer#15]
希望可以显示出`echo srvr | nc zkIP地址  端口`所打印出来的信息，例如角色、当前事务id、node数等。

如果服务器开启了 `echo srvr | nc zkIP地址  端口` 还可以显示出当台服务器的所有客户端连接

**Comment by xin497668869** [comment]
![image](https://user-images.githubusercontent.com/8223115/89906513-13f25680-dc1e-11ea-82f8-494742891aca.png)
已更新,点击即可看到
