### ISSUE TITLE
用zkCli可以连接，但这个貌似有点问题，提示也看不到错误信息

### ISSUE THREAD

**Issue by hhls** [xin497668869/zookeeper-visualizer#7]
如图![image](https://user-images.githubusercontent.com/23031435/54492725-f1162280-4903-11e9-8947-e306111ae02d.png)

**Comment by hhls** [comment]
是不是打开方式不对呢：）

**Comment by hhls** [comment]
> 是不是打开方式不对呢：）

果然是食用方式不对，我误将公司host当域名食用了，改为ip后就好了

**Comment by xin497668869** [comment]
新版本提供了查看日志功能和更完善的错误提示, 方便定位问题
