### ISSUE TITLE
看不到创建连接按钮了

### ISSUE THREAD

**Issue by littlecong** [xin497668869/zookeeper-visualizer#9]
![图片](https://user-images.githubusercontent.com/1177264/76919179-1ff21a80-6903-11ea-8a46-09e2a6543ba8.png)
oracle jdk1.8.0_144
  没有创建连接的按钮了，老版本还是有的

**Comment by xin497668869** [comment]
在列表那里右键就有了

**Comment by xin497668869** [comment]
发现列表为空时有个bug无法右键创建. 已经修复, 麻烦拉下最新代码
